server:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 7s
  writeTimeout: 7s

app:
  test: true

jwt:
  accessTokenTTL: 72h
  refreshTokenTTL: 720h

ldap:
  baseDn: "ou=groups,dc=it-college,dc=ru" # people/teachers

limiter:
  rps: 4
  burst: 10
  ttl: 10m